version: "3"
services:
    web:
        build: .
        ports: 
            - "8000:80"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server:2019-latest-ubuntu"
        environment: 
            SA_PASSWORD: "admin"
            ACCEPT_EULA: "Y"